from __future__ import annotations

from datetime import date, datetime, timezone
from decimal import Decimal

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    ForeignKey,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
    relationship,
)


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


class Base(DeclarativeBase):
    pass


# =============================================================
# DATA SOURCES
# =============================================================


class DataSource(Base):
    __tablename__ = "data_sources"

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    name: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
        unique=True,
    )

    short_name: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        unique=True,
    )

    website: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
    )

    is_primary: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )

    indicators: Mapped[list["Indicator"]] = relationship(
        back_populates="source"
    )


# =============================================================
# INDICATORS
# =============================================================


class Indicator(Base):
    __tablename__ = "indicators"

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    symbol: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        unique=True,
        index=True,
    )

    name: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
    )

    category: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    frequency: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )

    units: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )

    source_id: Mapped[int] = mapped_column(
        ForeignKey("data_sources.id"),
        nullable=False,
    )

    active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )

    source: Mapped["DataSource"] = relationship(
        back_populates="indicators"
    )

    observations: Mapped[list["Observation"]] = relationship(
        back_populates="indicator",
        cascade="all, delete-orphan",
    )


# =============================================================
# OBSERVATIONS
# =============================================================


class Observation(Base):
    __tablename__ = "observations"

    __table_args__ = (
        UniqueConstraint(
            "indicator_id",
            "observation_date",
            name="uq_observation_indicator_date",
        ),
    )

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    indicator_id: Mapped[int] = mapped_column(
        ForeignKey("indicators.id"),
        nullable=False,
        index=True,
    )

    observation_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        index=True,
    )

    value: Mapped[Decimal] = mapped_column(
        Numeric(20, 8),
        nullable=False,
    )

    retrieved_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )

    indicator: Mapped["Indicator"] = relationship(
        back_populates="observations"
    )


# =============================================================
# NEWS SNAPSHOTS
# =============================================================


class NewsSnapshot(Base):
    """
    One stored market-news assessment per business day.

    The complete classified news payload is retained
    as JSON text so the presentation layer can read
    the same snapshot that was generated by the
    scheduled news-refresh job.
    """

    __tablename__ = "news_snapshots"

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    snapshot_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        unique=True,
        index=True,
    )

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
    )

    market_attention: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )

    directional_confirmation: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    funding_severity: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )

    system_liquidity_severity: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )

    summary: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    payload_json: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
    )

# =============================================================
# TREASURY AUCTIONS
# =============================================================


class TreasuryAuctionRecord(Base):
    """
    One Treasury auction record from Treasury FiscalData.

    Unlike ordinary Indicator/Observation time series,
    auctions are structured records with an announcement
    lifecycle:

        announcement
            ↓
        auction
            ↓
        settlement / issue

    The same CUSIP may be reopened, so CUSIP alone is not
    unique. CUSIP + auction date identifies one auction.
    """

    __tablename__ = "treasury_auctions"

    __table_args__ = (
        UniqueConstraint(
            "cusip",
            "auction_date",
            name="uq_treasury_auction_cusip_date",
        ),
    )

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    # ---------------------------------------------------------
    # IDENTIFICATION
    # ---------------------------------------------------------

    cusip: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
    )

    record_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
    )

    security_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )

    security_term: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )

    # ---------------------------------------------------------
    # DATES
    # ---------------------------------------------------------

    announcement_date: Mapped[date | None] = mapped_column(
        Date,
        nullable=True,
        index=True,
    )

    auction_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        index=True,
    )

    issue_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        index=True,
    )

    maturity_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
    )

    # ---------------------------------------------------------
    # SECURITY CHARACTERISTICS
    # ---------------------------------------------------------

    reopening: Mapped[bool | None] = mapped_column(
        Boolean,
        nullable=True,
    )

    cash_management_bill: Mapped[bool | None] = mapped_column(
        Boolean,
        nullable=True,
    )

    # ---------------------------------------------------------
    # SUPPLY
    # ---------------------------------------------------------

    offering_amount_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    currently_outstanding_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    estimated_public_maturing_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    # ---------------------------------------------------------
    # AUCTION DEMAND
    # ---------------------------------------------------------

    competitive_tendered_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    competitive_accepted_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    noncompetitive_accepted_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    fima_tendered_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    fima_accepted_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    soma_tendered_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    soma_accepted_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    total_tendered_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    total_accepted_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    # ---------------------------------------------------------
    # BIDDER DISTRIBUTION
    # ---------------------------------------------------------

    primary_dealer_tendered_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    primary_dealer_accepted_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    indirect_bidder_tendered_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    indirect_bidder_accepted_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    direct_bidder_tendered_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    direct_bidder_accepted_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    treasury_retail_accepted_dollars: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(24, 4),
        nullable=True,
    )

    # ---------------------------------------------------------
    # PRICING
    # ---------------------------------------------------------

    bid_to_cover_ratio: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(12, 6),
        nullable=True,
    )

    high_investment_rate: Mapped[
        Decimal | None
    ] = mapped_column(
        Numeric(12, 6),
        nullable=True,
    )

    # ---------------------------------------------------------
    # AUDIT
    # ---------------------------------------------------------

    retrieved_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
    )
    